// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "proplist.h"

/////////////////////////////////////////////////////////////////////////////
// CPropList

IMPLEMENT_DYNCREATE(CPropList, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPropList properties

short CPropList::GetPrecision()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CPropList::SetPrecision(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

long CPropList::GetBorderStyle()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CPropList::SetBorderStyle(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

BOOL CPropList::GetShowDescription()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CPropList::SetShowDescription(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CPropList operations

void CPropList::Clear()
{
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CPropList::AddProperty(LPCTSTR Category, LPCTSTR Caption, const VARIANT& Value, LPCTSTR Description, long ButtonType, BOOL IsEnabled)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_VARIANT VTS_BSTR VTS_I4 VTS_BOOL;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Category, Caption, &Value, Description, ButtonType, IsEnabled);
}

void CPropList::SetValue(LPCTSTR PropertyName, const VARIANT& Value)
{
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PropertyName, &Value);
}

void CPropList::CloseAll()
{
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CPropList::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
