//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SubstationInternals.rc
//
#define IDS_PROJNAME                    100
#define Frm_Substation                  200
#define Frm_SubstationDet_Kiosk         201
#define Frm_SubstationDetails           202
#define Frm_SubstationDet_PT            203
#define IDD_RENAMEDLG                   205
#define IDD_LAYOUT                      208
#define IDD_LAYOUT_OLD                  208
#define IDD_LAYOUT_NEW                  209
#define IDC_Schematic                   500
#define IDC_COMBO11                     501
#define IDC_CBITEM1                     501
#define IDC_Substation                  502
#define IDC_CBPTLENGTH                  502
#define IDC_CBSSSIZE                    503
#define IDC_CBPTSTRENGTH                503
#define IDC_LBLTRANSFORMER              504
#define IDC_CBITEM16                    504
#define IDC_BTNSSDETAILS                505
#define IDC_COMBO12                     505
#define IDC_CBITEM2                     505
#define IDC_CBHVCEQUIP                  506
#define IDC_COMBO13                     506
#define IDC_CBITEM3                     506
#define IDC_COMBO14                     507
#define IDC_CBITEM5                     507
#define IDC_COMBO10                     508
#define IDC_COMBO15                     508
#define IDC_CBLVCFUSE                   508
#define IDC_CBITEM4                     508
#define IDC_STATIC3                     509
#define IDC_CBLVCFUSE2                  509
#define IDC_STATIC6                     510
#define IDC_COMBO16                     510
#define IDC_LBLLVCONNECTIONS            510
#define IDC_CBITEM6                     510
#define IDC_STATIC4                     511
#define IDC_COMBO17                     511
#define IDC_LBLHVCONN                   511
#define IDC_CBITEM7                     511
#define IDC_SUBSTATIONTYPE              512
#define IDC_COMBO18                     512
#define IDC_CBSSTYPE                    512
#define IDC_CBITEM8                     512
#define IDC_EDIT1                       513
#define IDC_COMBO19                     513
#define IDC_EDITRENAME                  513
#define IDC_CBITEM9                     513
#define IDC_EDIT2                       514
#define IDC_COMBO20                     514
#define IDC_EDITSSNUMBER                514
#define IDC_CBITEM10                    514
#define IDC_EDIT3                       515
#define IDC_COMBO21                     515
#define IDC_EDITSSNAME                  515
#define IDC_CBITEM11                    515
#define IDC_COMBO3                      516
#define IDC_COMBO22                     516
#define IDC_CBSSDESCRIPTION             516
#define IDC_CBITEM12                    516
#define IDC_COMBO4                      517
#define IDC_COMBO23                     517
#define IDC_CBSSSTOCKTYPE               517
#define IDC_CBITEM13                    517
#define IDC_EDIT4                       518
#define IDC_COMBO24                     518
#define IDC_EDITHVCNUMBER               518
#define IDC_CBITEM14                    518
#define IDC_COMBO6                      519
#define IDC_COMBO25                     519
#define IDC_CBHVCTYPE                   519
#define IDC_CBITEM15                    519
#define IDC_COMBO7                      520
#define IDC_CBHVCRATING                 520
#define IDC_EDIT5                       521
#define IDC_EDITSIDEA                   521
#define IDC_EDIT6                       522
#define IDC_EDITDETAILS1                522
#define IDC_CHECK1                      523
#define IDC_EDIT20                      523
#define IDC_CHKEFIA                     523
#define IDC_EDITDETAILS2                523
#define IDC_CHECK2                      524
#define IDC_EDIT21                      524
#define IDC_CHKEFIB                     524
#define IDC_EDITDETAILS3                524
#define IDC_COMBO8                      525
#define IDC_EDIT22                      525
#define IDC_CBTFRATING                  525
#define IDC_CBTXRATING                  525
#define IDC_EDITDETAILS5                525
#define IDC_EDIT7                       526
#define IDC_EDITDETAILS4                526
#define IDC_EDIT8                       527
#define IDC_EDIT23                      527
#define IDC_EDITTXPHASES                527
#define IDC_EDITDETAILS6                527
#define IDC_COMBO9                      528
#define IDC_EDIT24                      528
#define IDC_CBTFTAPRATIO                528
#define IDC_CBTXTAPRATIO                528
#define IDC_EDITDETAILS7                528
#define IDC_EDIT9                       529
#define IDC_EDIT25                      529
#define IDC_EDITTXTAPSETTING            529
#define IDC_EDITDETAILS8                529
#define IDC_TAB1                        530
#define IDC_EDIT26                      530
#define IDC_TABLVC                      530
#define IDC_EDITDETAILS9                530
#define IDC_OK                          531
#define IDC_CHECK3                      531
#define IDC_EDIT27                      531
#define IDC_CHKLVCWDNO                  531
#define IDC_EDITDETAILS10               531
#define IDC_CANCEL                      532
#define IDC_CHECK4                      532
#define IDC_EDIT28                      532
#define IDC_CHKLVCEFI                   532
#define IDC_CHKLVCIDLINK                532
#define IDC_EDITDETAILS11               532
#define IDC_EDIT10                      533
#define IDC_EDIT29                      533
#define IDC_EDITLVCPANELRATING          533
#define IDC_EDITDETAILS12               533
#define IDC_EDIT11                      534
#define IDC_EDIT30                      534
#define IDC_EDITLVCDISTNAME             534
#define IDC_EDITDETAILS13               534
#define IDC_EDIT12                      535
#define IDC_CBSSSTOCKTYPE2              535
#define IDC_CBLVNOOFDIST                535
#define IDC_EDITPTSSNAME                535
#define IDC_EDIT13                      536
#define IDC_EDITPTTXRATING              536
#define IDC_TABLVC2                     536
#define IDC_EDIT14                      537
#define IDC_EDITPTSIZE                  537
#define IDC_CHKLVCWDNO2                 537
#define IDC_EDIT15                      538
#define IDC_EDITPTNUMBER                538
#define IDC_CHKLVCIDLINK2               538
#define IDC_EDIT16                      539
#define IDC_EDITPTPREFIX                539
#define IDC_EDITLVCPANELRATING2         539
#define IDC_EDIT17                      540
#define IDC_EDIT18                      541
#define IDC_EDITSSPREFIX                541
#define IDC_EDIT31                      542
#define IDC_EDITSSOPTIONS               542
#define IDC_EDITDETAILS14               542
#define IDC_EDIT19                      543
#define IDC_LBLSUBSTATION               543
#define IDC_EDITPTTYPE                  543
#define IDC_EDIT32                      544
#define IDC_LBLSSTYPE                   544
#define IDC_EDITDETAILS15               544
#define IDC_EDIT33                      545
#define IDC_LBLSSSIZE                   545
#define IDC_EDITMASTEROPTIONS           545
#define IDC_LBLSSPREFIX                 546
#define IDC_LBLSSNUMBER                 547
#define IDC_LBLSS                       548
#define IDC_LBLSSNAME                   549
#define IDC_LBLSSDESC                   550
#define IDC_LBLSSSTKTYPE                551
#define IDC_LBLSSOPTIONS                552
#define IDC_LBLHVCNUMBER                553
#define IDC_LBLHVCEQUIP                 554
#define IDC_LBLHVCTYPE                  555
#define IDC_LBLHVCRATING                556
#define IDC_LBLHVCPROTECTION            557
#define IDC_CBLVCFUSEA                  558
#define IDC_LBLSIDEA                    559
#define IDC_LAYOUTS_IN_DWG              559
#define IDC_LBLSIDEB                    560
#define IDC_EDITSIDEB                   561
#define IDC_LBLTXRATING                 562
#define IDC_LBLTXVOLTAGE                563
#define IDC_LBLTXPHASES                 564
#define IDC_LBLTXTAPRATIO               565
#define IDC_LBLTX                       566
#define IDC_EDITTXVOLTAGE               567
#define IDC_LBLTXTAPSETTING             568
#define IDC_LBLTXMDI                    569
#define IDC_LBLTXCTRATIO                570
#define IDC_LBLTXKFACTOR                571
#define IDC_LBLTXLENGTH                 572
#define IDC_LBLTXSTRENGTH               573
#define IDC_EDITTXCTRATIO               574
#define IDC_EDITTXKFACTOR               575
#define IDC_EDITTXLENGTH                576
#define IDC_EDITTXSTRENGT               577
#define IDC_EDITTXSTRENGTH              577
#define IDC_LBLLVCDISTNO                578
#define IDC_LBLLVCNOOFDIST              579
#define IDC_LBLLVCPANELRATING           580
#define IDC_LBLLVCFUSEA                 581
#define IDC_LBLLVCFUSE                  582
#define IDC_LBLLVCDISTNAME              583
#define IDCLEAR                         584
#define IDC_LBLSSDETAILS                585
#define IDC_LBLKSSDETAILS               585
#define IDC_CBLVCFUSEA2                 585
#define IDC_LBLEA                       586
#define IDC_LBLKEA                      586
#define IDC_LBLOPTION                   587
#define IDC_EDITSSTYPE                  588
#define IDC_EDITKSSTYPE                 588
#define IDC_EDITSSSIZE                  589
#define IDC_EDITKSSSIZE                 589
#define IDC_EDITSSEA                    590
#define IDC_EDITKSSEA                   590
#define IDC_COMBOSSOPTION               591
#define IDC_CBKSSOPTION                 591
#define IDC_LBLKSSTYPE                  592
#define IDC_LBLKSSSIZE                  593
#define IDC_LBLKSSPREFIX                594
#define IDC_LBLKSSNUMBER                595
#define IDC_LBLKSS                      596
#define IDC_LBLKSSNAME                  597
#define IDC_EDITKSSNAME                 598
#define IDC_EDITKSSPREFIX               599
#define IDC_EDITKSSNUMBER               600
#define IDC_COMBO_LAYOUTS               602
#define IDC_COMBO_LAYOUTS_NEW           606

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         607
#define _APS_NEXT_SYMED_VALUE           130
#endif
#endif
